name: ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
        os: [macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: clone tree-sitter
        run: |
          git clone https://github.com/tree-sitter/tree-sitter local-tree-sitter
      - name: build tree-sitter
        run: |
          cd local-tree-sitter
          make
      - name: install tree-sitter
        run: |
          cd local-tree-sitter
          sudo make install
      - name: bundle install
        run: |
          bundle install
      - name: compile
        run: |
          bundle exec rake compile
      - name: test
        run: |
          bundle exec rake test
